# Backdrop recipe
name: forum
recipe: backdrop

config:
  php: '7.2'
  via: nginx
  webroot: www
  backdrush: stable
  xdebug: true

services:
  database:
    type: mariadb
    portforward: 3308
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://forum.lndo.site
