# Backdrop recipe
name: forum
recipe: backdrop

config:
  php: '7.2'
  via: nginx
  webroot: www
  backdrush: 1.0.0
  xdebug: true

services:
  database:
    type: mariadb:10.3
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://forum.lndo.site
