services:
  php:
    image: tugboatqa/php:7.2-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Install PHP 'zip' extension to allow installing Backdrop modules.
        - docker-php-ext-install zip
        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite
        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT/www $DOCROOT
        # Use the Tugboat-specific Backdrop settings.
        - cp $TUGBOAT_ROOT/.tugboat/settings.local.php $TUGBOAT_ROOT/www/settings.local.php
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> $TUGBOAT_ROOT/www/settings.local.php
        # Download a copy of the latest database & files directory.
        - php $TUGBOAT_ROOT/scripts/pull-db-files.php --database
        - gunzip forum-latest-sanitized.sql.gz
        - php $TUGBOAT_ROOT/scripts/pull-db-files.php --files
        - tar -xzf forum-files-latest.tar.gz && rm forum-files-latest.tar.gz
      build:
        # Delete previous comments in the PR.
        - cd $TUGBOAT_ROOT/.tugboat && ./delete-comments.sh
        # Generate and store a random password for the admin user.
        - openssl rand -hex 6 > $TUGBOAT_ROOT/.tugboat/password
        # Import the sanitized database.
        - mysql -u tugboat -ptugboat tugboat < forum-latest-sanitized.sql
        # Replace the files directory.
        - rm -r $TUGBOAT_ROOT/www/files && cp -r $TUGBOAT_ROOT/files $TUGBOAT_ROOT/www
        # Update config.
        - rm $TUGBOAT_ROOT/config/live-active/*.json
        - cp $TUGBOAT_ROOT/config/staging/*.json $TUGBOAT_ROOT/config/live-active
        # Set appropriate file permissions/ownership.
        - chown -R www-data:www-data $TUGBOAT_ROOT/www
        - find $TUGBOAT_ROOT/www/files $TUGBOAT_ROOT/www/layouts $TUGBOAT_ROOT/www/modules $TUGBOAT_ROOT/www/themes -type d -exec chmod 2775 {} \;
        - find $TUGBOAT_ROOT/www/files $TUGBOAT_ROOT/www/layouts $TUGBOAT_ROOT/www/modules $TUGBOAT_ROOT/www/themes -type f -exec chmod 0664 {} \;
        # Post a comment in the PR.
        - cd $TUGBOAT_ROOT/.tugboat && ./post-comment.sh
  mariadb:
    image: tugboatqa/mariadb:latest
    commands:
      init:
        # Configure database for UTF-8: https://api.backdropcms.org/database-configuration#utf8mb4
        - echo "[mysqld]\ninnodb_large_prefix=true\ninnodb_file_format=barracuda\ninnodb_file_per_table=true" >> /etc/mysql/conf.d/utf8mb.conf
